// react-app/src/App.jsx
import { ReactComponent as PlusIcon } from './assets/icons/plus_icon.svg'
import { ReactComponent as CartIcon } from './assets/icons/cart_icon.svg'
import { ReactComponent as BinIcon } from './assets/icons/bin_icon.svg'
import books from './data/books'

function App() {
  return (
    <div className='app'>
      <header className='header'>
        <a href='/' className='logo'>
          book<span>shelf</span>
        </a>
        <button className='cart-trigger'>
          <span>Cart</span>
          <CartIcon />
        </button>
        <div className='cart'></div>
      </header>

      <main>
        <h1>Books</h1>
        <div className='grid'>
          {books.map((book, index) => (
            <div className='grid-item' key={index}>
              <div className='image-wrap'>
                <button className='add-btn'>
                  <PlusIcon />
                </button>
                <img className='image' src={`${process.env.PUBLIC_URL}/images/${book.id}.jpg`} alt='' />
                <p>{book.price}</p>
              </div>
              <h3>{book.title}</h3>
              <p>by - {book.author}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}

export default App

// vue-app/src/App.vue
<template>
  <header class="header">
    <a href="/" class="logo">book<span>shelf</span> </a>
    <button className="cart-trigger">
      <span>Cart</span>
      <inline-svg src="/assets/icons/cart_icon.svg" />
    </button>
    <div class="cart"></div>
  </header>

  <main>
    <h1>Books</h1>
    <div class="grid">
      <div v-for="(book, index) in books" :key="index" class="grid-item">
        <div class="image-wrap">
          <button class="add-btn">
            <inline-svg src="/assets/icons/plus_icon.svg" />
          </button>
          <img class="image" :src="`/assets/images/${book.id}.jpg`" alt="" />
          <p>{{ book.price }}</p>
        </div>
        <h3>{{ book.title }}</h3>
        <p>by - {{ book.author }}</p>
      </div>
    </div>
  </main>
</template>

<script>
import InlineSvg from "vue-inline-svg";
import books from "./data/books";

export default {
  name: "App",
  components: {
    InlineSvg,
  },
  data() {
    return {
      books,
    };
  },
};
</script>

<style src="./../src/styles/main.scss" lang="scss"></style>
